### ISSUE TITLE
FGA homepage is gone; perhaps move it to GitHub?

### ISSUE THREAD

**Issue by fingolfin** [chsievers/fga#5]
As you know, the FGA homepage is gone.

A simple fix would be to move the FGA homepage to GitHub, then make a new release with `PackageInfo.g` updated to point to the new homepage. This is very easy to do by using these two together:
* https://github.com/gap-system/GitHubPagesForGAP
* https://github.com/gap-system/ReleaseTools

If one has done it before, it's a matter of 30 minutes work or so; subsequent releases can then be done with the `release` script in less than a minute (well, plus whatever time one needs to make the actual changes for the release, of course ;-)

@chsievers If you don't have time or interest right now to work on updating this package (and merging my PR #4 ;-), we could also help with this, by moving this package to the `gap-package` organization; then, with your permission, we can make all the required changes to move the package homepage to GitHub, and make a release with fixed URLs.

**Comment by fingolfin** [comment]
@chsievers any comments?

**Comment by olexandr-konovalov** [comment]
Would be really useful to have a new release with improved testing as done in #4. Otherwise, we can not automatically analyse the outcome of package tests. Instead, they are in the "staging" area - please see https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging to inspect them: click on the line corresponding to this package and scroll till the very end of the log file to see the output of the package tests, the summary, and further instructions.

As soon as the package tests will run without diffs, they will be moved to https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9. This will be very helpful to monitor in the future that the package is still usable and that no changes in the GAP system break the package.

**Comment by fingolfin** [comment]
@chsievers it seems the old data is gone, so you will have to setup a new website eventually.

**Comment by chsievers** [comment]
Closing this since homepage is back and new release published.

**Comment by olexandr-konovalov** [comment]
Please submit PR to https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList with the new URL if the package updates should be now ready for picking up. Remember to use `MOVE` command to enforce new URL in case you can not put the new PackageInfo.g in the old location.

**Comment by chsievers** [comment]
@alex-konovalov There is no new URL. The new version is at the old location and ready for picking up.
